---
title: "Fourth Model Attempt"
author: "Anthony Arroyo"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  pdf_document:
    pandoc_args: --listings
    includes:
      in_header: preamble.tex
params:
  sample_param:
    value: 0
---
\newcommand{\br}{\hfill\break}
\newcommand{\brsp}{\vspace{8pt}\hfill\break}
```{r header, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(magrittr)
library(here)
library(reshape2)

invisible(lapply(list.files(here::here("R"), "\\.R$", full.names = TRUE), source))
(function() { set.seed(8675309) })()
```

```{r private, include=FALSE}
```

```{r dataload, warning=FALSE}
finance = LoadMarketData()
brooklyn = PipelineBrooklyn()
brook = brooklyn %>%
  CleanTons(.) %>%
    CleanInfluencers(.) %>%
      dplyr::filter(., factryarea < 1, retailarea < 1) %>%
        dplyr::select(., -factryarea, -retailarea) %>%
          RemoveInfluencers(., lm(y~., .), 4) %>%
            RemoveInfluencers(., lm(y~., .), 4)

fixer2 = PreProcessExp2(brook)
fixer3 = PreProcessExp3(brook)
fixer4 = PreProcessExp4(brook)
fixer5 = PreProcessExp5(brook)

crossValid = caret::trainControl(method = "cv", number = 5)

tts = brook %>%
  PreProcessApply(., fixer2) %>%
    rsample::initial_split(.)

# randomness
# outliers
# homodeskicity
# transform
```

```{r}
PlotVarDistribution(brook)
```

```{r}
brookNum = brook[, sapply(brook, is.numeric)]
#(brookLm = lm(y ~ . - unitsres - numfloors - lotarea - UNRATE - GDP - PPIACO, brook)) %>%
(brookLm = lm(y ~ ., brook)) %>%
  summary(.)
```

```{r}
# Optimal at y^0.6
sapply(seq_len(200) / 100, function(x) {
  brook %>%
    dplyr::mutate(y = y^x) %>%
      lm(y ~ ., .) %>%
        summary(.) %>%
          .$r.squared
  
})
```

```{r}
sapply(list(fixer2, fixer3, fixer4, fixer5), function(x) {
  brook %>%
    PreProcessApply(., x) %>%
      lm(y ~ ., .) %>%
        summary(.) %>%
          .$r.squared
  
})
```

```{r}
PlotCorrEllipse(cor(brookNum))
```

```{r}
heatmap(cor(brookNum))
```

```{r}
CorrelationFunnel(brookNum, "y", 4, showPlot = TRUE)
```

```{r}
pca = prcomp(scale(brookNum))
summary(pca)
pca
```

```{r}
modelOne = lm(y ~ ., rsample::training(tts)[-c(2000, 46308), ])

summary.lm(modelOne)
```

```{r}
.PlotFour(modelOne)
```

```{r}
PlotLinearity(modelOne)
PlotDistribution(modelOne)
PlotQQuantile(modelOne)
```

## Model 2 - Full Model without Finance

```{r}
modelTwo = lm(y ~ ., ExperimentTwo(rsample::training(tts)))

summary.lm(modelTwo)
```

```{r}
.PlotFour(modelTwo)
```

## Model 3 - Reduced Model with Finance

```{r}
modelThree = lm(y ~ ., ExperimentThree(rsample::training(tts)))

summary.lm(modelThree)
```

```{r}
.PlotFour(modelThree)
```

## Model 4-6 - Poisson Regression Models

```{r}
modelFour = glm(y ~ ., rsample::training(tts), family = poisson(link = "log"))
modelFive = glm(y ~ ., ExperimentTwo(rsample::training(tts)), family = poisson(link = "log"))
modelSix = glm(y ~ ., ExperimentThree(rsample::training(tts)), family = poisson(link = "log"))
```


```{r}
summary(modelFour)
.PlotFour(modelFour)
```

```{r}
summary(modelFive)
.PlotFour(modelFive)
```

```{r}
summary(modelSix)
.PlotFour(modelSix)
```

# Model Selection

```{r}
#stats::anova(test = "Chisq", modelOne, modelTwo, modelThree)
#Error in anova.lmlist(object, ...) : models were not all fitted to the same size of dataset
```

```{r}
stats::anova(test = "Chisq", modelFour, modelFive, modelSix)
```

## Linear Regression Metrics

```{r}
LinearModelStatistics(list(modelOne, modelTwo, modelThree), rsample::testing(tts))
```

## Poisson Model Metrics

```{r}
list(modelFour, modelFive, modelSix) %>%
  lapply(predict, rsample::testing(tts)) %>%
    { data.frame(
      Model = c("Model Four", "Model Five", "Model Six"),
      RMSE = sapply(., ModelMetrics::rmse, rsample::testing(tts)$y),
      AIC = sapply(list(modelFour, modelFive, modelSix), stats::AIC)
    )}
```

## T-Test disparate models

```{r}
list(modelOne, modelFour) %>%
  lapply(predict, rsample::testing(tts)) %>%
    { t.test(.[[1]], .[[2]], alternative = "two.sided", paired = TRUE) }
```

## Visualization of Predictions

```{r}
comparison = list(modelOne, modelFour) %>%
  lapply(predict, rsample::testing(tts)) %>%
    { do.call(cbind, .) } %>%
      { cbind(seq_len(length(.[, 1])), rsample::testing(tts)$y, .) } %>%
        magrittr::set_colnames(c("INDEX", "y", "LinearModel", "PoissonModel")) %>%
          as.data.frame(.)

lattice::xyplot(INDEX ~ y, data = comparison)
lattice::xyplot(INDEX ~ LinearModel, data = comparison)
lattice::xyplot(INDEX ~ PoissonModel, data = comparison)
```

# Visualization of predictions to actual

```{r}
comparison %>%
  ggplot2::ggplot(.) +
  ggplot2::aes(x = LinearModel, y = y) +
  ggplot2::geom_point(shape = "circle", size = 1.5, colour = "#11244644") +
  ggplot2::geom_abline(slope = 1, size = 3, color = "#ff0000") +
  ggplot2::theme_minimal()
```

