---
title: "First Model Attempt"
author: "Anthony Arroyo"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  pdf_document:
    pandoc_args: --listings
    includes:
      in_header: preamble.tex
params:
  sample_param:
    value: 0
---
\newcommand{\br}{\hfill\break}
\newcommand{\brsp}{\vspace{8pt}\hfill\break}
```{r header, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(magrittr)
library(here)
library(reshape2)
library(rvest)

invisible(lapply(list.files(here::here("R"), "\\.R$", full.names = TRUE), source))
(function() { set.seed(8675309) })()
```

```{r private, include=FALSE}
```

```{r dataload, warning=FALSE}
sales = LoadBrooklynSalesMap()
rolling = LoadDoF()
salesData = PrepareBrooklyn(sales)
```

```{r very-simple-model}
badCols = c("easement", "ZoneDist4", "SPDist3")
badInds = which(colnames(salesData) %in% badCols)
crossValid = caret::trainControl(method = "cv", number = 3)
train = salesData[! is.na(salesData$y), -badInds] %>%
  .[, seq_len(30)] %>%
    tidyr::drop_na() %>%
      .[, ! sapply(., is.factor)]

baseForest = train(y ~ ., method = "rf", trControl = crossValid, ntree = 300, data = train)
forest = randomForest::randomForest(train[, -1], train[, 1])
```


